[env:seeed_xiao_esp32c6]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = seeed_xiao_esp32c6
framework = arduino
monitor_speed = 115200

# This line gives your app 3MB of space (Fixes the length error)
board_build.partitions = huge_app.csv

# This ensures the C6 uses the correct USB CDC for Serial output
build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

lib_deps =
    adafruit/Adafruit ILI9341
    adafruit/Adafruit GFX Library
    adafruit/Adafruit BME280 Library
    adafruit/Adafruit SGP30 Sensor
    adafruit/Adafruit TSL2591 Library
    adafruit/Adafruit BusIO
    bblanchon/ArduinoJson
    https://github.com/tzapu/WiFiManager.git