[env:seeed_xiao_esp32c6]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = seeed_xiao_esp32c6
framework = arduino
monitor_speed = 115200

board_build.partitions = huge_app.csv

build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -Wno-error=return-type
    -Wno-deprecated-enum-enum-conversion

lib_ignore =
    ArduSensorPlatformCoreBase
    UartCommunicatior

lib_deps =
    adafruit/Adafruit ILI9341
    adafruit/Adafruit GFX Library
    adafruit/Adafruit TSL2591 Library
    adafruit/Adafruit BusIO
    https://github.com/Sensirion/arduino-i2c-scd4x.git
    https://github.com/Sensirion/arduino-i2c-sgp41.git
    https://github.com/Sensirion/arduino-gas-index-algorithm.git
    bblanchon/ArduinoJson
    https://github.com/tzapu/WiFiManager.git